version: "3.7"

services:
    # main:
    #     build:
    #         context: ./main
    #     image: main
    #     ports:
    #         - 19350:19350
    #     networks:
    #         - bx-net
    # backup:
    #     build:
    #         context: ./backup
    #     image: backup
    #     ports:
    #         - 19351:19351
    #     networks:
    #         - bx-net
    # edge1:
    #     build:
    #         context: ./edge1
    #     image: edge1
    #     ports:
    #         - 1935:1935
    #     networks:
    #         - bx-net
    vapror:
        build:
            context: ./vapror
        image: vapror
        network_mode: host   
# networks:
#     bx-net:
#         driver: bridge